In [1]:
import pandas as pd

df = pd.read_csv('/Users/josephtoniodavid/Documents/credit-risk-analysis/raw_cr_loan2.csv')

df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [4]:
df.drop_duplicates(inplace = True)

In [6]:
print(df.duplicated())

0        False
1        False
2        False
3        False
4        False
         ...
32576    False
32577    False
32578    False
32579    False
32580    False
Length: 32416, dtype: bool

In [7]:
print(df.corr())

                            person_age  person_income  person_emp_length  \
person_age                    1.000000       0.173293           0.163001
person_income                 0.173293       1.000000           0.133903
person_emp_length             0.163001       0.133903           1.000000
loan_amnt                     0.050680       0.265947           0.113183
loan_int_rate                 0.011760       0.000878          -0.056607
loan_status                  -0.022698      -0.145005          -0.082817
loan_percent_income          -0.042300      -0.254472          -0.053999
cb_person_cred_hist_length    0.859215       0.117614           0.144889

                            loan_amnt  loan_int_rate  loan_status  \
person_age                   0.050680       0.011760    -0.022698
person_income                0.265947       0.000878    -0.145005
person_emp_length            0.113183      -0.056607    -0.082817
loan_amnt                    1.000000       0.146937     0.105736
loan_int_rate                0.146937       1.000000     0.335853
loan_status                  0.105736       0.335853     1.000000
loan_percent_income          0.572824       0.120207     0.379697
cb_person_cred_hist_length   0.041865       0.015896    -0.016498

                            loan_percent_income  cb_person_cred_hist_length
person_age                            -0.042300                    0.859215
person_income                         -0.254472                    0.117614
person_emp_length                     -0.053999                    0.144889
loan_amnt                              0.572824                    0.041865
loan_int_rate                          0.120207                    0.015896
loan_status                            0.379697                   -0.016498
loan_percent_income                    1.000000                   -0.031457
cb_person_cred_hist_length            -0.031457                    1.000000

In [9]:
for x in df.index:
  if df.loc[x, "person_emp_length"] > 120 or df.loc[x, "person_age"] > 120:
    df.drop(x, inplace = True)

In [13]:
x = df["loan_amnt"].mode()
x

0    10000
Name: loan_amnt, dtype: int64